Sprint 3
ff1892/middle.messenger.praktikum.yandex pull request #3
Opened 2022-11-25 12:06 UTC by ff1892

2022-11-25 13:38 UTC, ff1892 commented
Тест падает, потому что уходит в бесконечный билд Parcel. Локально и на Netlify билд работает нормально.

2022-11-25 17:24 UTC, podlovchenko requested changes
Привет)
При сборке локально ошибка
<img width="1164" alt="Снимок экрана 2022-11-25 в 19 49 31" src="https://user-images.githubusercontent.com/22602747/204032074-9224da17-1f9f-4d76-aa02-9a1f25f05a89.png">
Нет редиректа на страницу чатов, если пользователь уже в системе

2022-11-25 17:24 UTC, podlovchenko commented on package.json
> +    "start": "parcel build src/index.html --no-source-maps --dist-dir ./dist && node src/server.js",
Лучше периспользовать npm run build

2022-11-25 19:12 UTC, ff1892 commented on package.json
> +    "start": "parcel build src/index.html --no-source-maps --dist-dir ./dist && node src/server.js",
Привет! 🙂 

Интересно. У меня из-за этой ошибки тесты падали, а локально все ок было. Переустановил parcel на последнюю версию - тесты прошли. 

Редирект залогиненного пользователя настроил.

2022-11-26 11:59 UTC, podlovchenko commented
Спасибо за оперативные правки, все хорошо, работу принимаю)

2022-11-26 12:25 UTC, ff1892 commented
Спасибо!

2022-11-27 08:06 UTC, merged